export type TopicId =
  | "education"
  | "environment"
  | "technology"
  | "health"
  | "urbanisation"
  | "work"
  | "globalisation"
  | "media";

export type Topic = { id: TopicId; name: string; blurb: string; color: string };

export const topics: Topic[] = [
  { id: "education", name: "Education", blurb: "Schools, universities, teaching and learning", color: "#4169d8" },
  { id: "environment", name: "Environment", blurb: "Climate, conservation and natural resources", color: "#16a36a" },
  { id: "technology", name: "Technology", blurb: "Automation, data and digital life", color: "#b34fc4" },
  { id: "health", name: "Health", blurb: "Lifestyle, medicine and public health", color: "#1f9d8b" },
  { id: "urbanisation", name: "Urbanisation", blurb: "Cities, transport and housing", color: "#f28a45" },
  { id: "work", name: "Work", blurb: "Employment, pay and the workplace", color: "#5b6bd6" },
  { id: "globalisation", name: "Globalisation", blurb: "Trade, migration and culture", color: "#0e7490" },
  { id: "media", name: "Media", blurb: "News, information and public debate", color: "#eb0000" },
];

export const topicById = Object.fromEntries(topics.map((t) => [t.id, t])) as Record<TopicId, Topic>;

export type Pos = "noun" | "verb" | "adjective" | "adverb" | "phrase";

export type WordEntry = {
  id: string;
  word: string;
  pos: Pos;
  band: 6 | 7 | 8;
  topic: TopicId;
  definition: string;
  /** The target word is wrapped in braces so drills can blank it out. */
  example: string;
  collocations: string[];
  synonyms: string[];
  note?: string;
};

export const words: WordEntry[] = [
  // ─── Education ───────────────────────────────────────────────────────────
  { id: "curriculum", word: "curriculum", pos: "noun", band: 6, topic: "education",
    definition: "the subjects that make up a course of study at a school or college",
    example: "Several countries have added coding to the national {curriculum}.",
    collocations: ["the national curriculum", "a broad curriculum", "curriculum reform"],
    synonyms: ["syllabus", "programme of study"],
    note: "The plural is curricula. Curriculum = the whole course; syllabus = one subject's content." },
  { id: "rote-learning", word: "rote learning", pos: "phrase", band: 7, topic: "education",
    definition: "learning by repeating something until you remember it, without understanding it",
    example: "Critics argue that {rote learning} produces students who cannot think independently.",
    collocations: ["rely on rote learning", "rote learning of facts"],
    synonyms: ["memorisation", "learning by heart"] },
  { id: "literacy", word: "literacy", pos: "noun", band: 6, topic: "education",
    definition: "the ability to read and write, or basic competence in a given field",
    example: "Adult {literacy} rates have risen steadily since the 1990s.",
    collocations: ["literacy rate", "digital literacy", "financial literacy"],
    synonyms: ["reading ability", "competence"],
    note: "The opposite is illiteracy. Extend it: digital literacy, media literacy." },
  { id: "vocational", word: "vocational", pos: "adjective", band: 7, topic: "education",
    definition: "relating to training for a particular job or trade rather than academic study",
    example: "{Vocational} courses in plumbing and engineering lead directly to employment.",
    collocations: ["vocational training", "vocational qualification", "vocational college"],
    synonyms: ["occupational", "job-related"] },
  { id: "tuition", word: "tuition", pos: "noun", band: 6, topic: "education",
    definition: "teaching, especially to a small group; also the fee charged for it",
    example: "Private {tuition} has become a significant household expense in many cities.",
    collocations: ["tuition fees", "private tuition", "one-to-one tuition"],
    synonyms: ["instruction", "teaching"] },
  { id: "scholarship", word: "scholarship", pos: "noun", band: 6, topic: "education",
    definition: "money awarded to a student to pay for their education, usually for merit or need",
    example: "She won a full {scholarship} to study engineering abroad.",
    collocations: ["award a scholarship", "a full scholarship", "merit-based scholarship"],
    synonyms: ["grant", "bursary"] },
  { id: "truancy", word: "truancy", pos: "noun", band: 8, topic: "education",
    definition: "the practice of staying away from school without permission",
    example: "Persistent {truancy} is closely linked to later unemployment.",
    collocations: ["tackle truancy", "truancy rates", "persistent truancy"],
    synonyms: ["absenteeism", "skipping school"] },
  { id: "holistic", word: "holistic", pos: "adjective", band: 8, topic: "education",
    definition: "dealing with the whole of something rather than only one part of it",
    example: "A {holistic} approach considers a child's emotional as well as academic growth.",
    collocations: ["a holistic approach", "holistic development", "holistic education"],
    synonyms: ["all-round", "comprehensive"] },

  // ─── Environment ─────────────────────────────────────────────────────────
  { id: "biodiversity", word: "biodiversity", pos: "noun", band: 7, topic: "environment",
    definition: "the variety of plant and animal life in a particular habitat",
    example: "Coral reefs support extraordinary {biodiversity} despite covering little of the ocean.",
    collocations: ["loss of biodiversity", "rich in biodiversity", "protect biodiversity"],
    synonyms: ["biological diversity", "variety of species"] },
  { id: "deforestation", word: "deforestation", pos: "noun", band: 6, topic: "environment",
    definition: "the cutting down of forests over a large area",
    example: "{Deforestation} in the Amazon accelerated during the dry season.",
    collocations: ["large-scale deforestation", "curb deforestation", "rates of deforestation"],
    synonyms: ["forest clearance", "logging"] },
  { id: "emissions", word: "emissions", pos: "noun", band: 6, topic: "environment",
    definition: "gases or other substances released into the air, especially by industry or vehicles",
    example: "The policy aims to halve carbon {emissions} within a decade.",
    collocations: ["carbon emissions", "cut emissions", "emissions targets"],
    synonyms: ["discharge", "output"] },
  { id: "sustainable", word: "sustainable", pos: "adjective", band: 6, topic: "environment",
    definition: "able to continue over time without damaging the environment or using up resources",
    example: "{Sustainable} farming keeps soil productive for future generations.",
    collocations: ["sustainable development", "environmentally sustainable", "sustainable growth"],
    synonyms: ["viable", "renewable"],
    note: "Overused in essays. Be specific: economically sustainable, environmentally sustainable." },
  { id: "renewable", word: "renewable", pos: "adjective", band: 6, topic: "environment",
    definition: "describing energy from sources that are naturally replaced, such as wind or sun",
    example: "{Renewable} sources now generate almost half the country's electricity.",
    collocations: ["renewable energy", "renewable sources", "shift to renewables"],
    synonyms: ["clean", "sustainable"] },
  { id: "conservation", word: "conservation", pos: "noun", band: 7, topic: "environment",
    definition: "the protection of the natural environment, wildlife or resources",
    example: "Marine {conservation} zones allow fish populations to recover.",
    collocations: ["wildlife conservation", "conservation efforts", "water conservation"],
    synonyms: ["preservation", "protection"] },
  { id: "degradation", word: "degradation", pos: "noun", band: 8, topic: "environment",
    definition: "the process by which the quality of something, especially land, is damaged",
    example: "Intensive agriculture has caused severe soil {degradation}.",
    collocations: ["environmental degradation", "land degradation", "severe degradation"],
    synonyms: ["deterioration", "decline"] },
  { id: "offset", word: "offset", pos: "verb", band: 8, topic: "environment",
    definition: "to balance one effect against an opposite one so that the result is reduced",
    example: "Airlines allow passengers to {offset} their flights by funding tree planting.",
    collocations: ["offset emissions", "carbon offsetting", "offset the cost"],
    synonyms: ["counterbalance", "compensate for"] },

  // ─── Technology ──────────────────────────────────────────────────────────
  { id: "automation", word: "automation", pos: "noun", band: 6, topic: "technology",
    definition: "the use of machines or computers to do work previously done by people",
    example: "{Automation} has transformed warehouses far faster than economists predicted.",
    collocations: ["increasing automation", "automation of tasks", "the threat of automation"],
    synonyms: ["mechanisation", "computerisation"] },
  { id: "obsolete", word: "obsolete", pos: "adjective", band: 7, topic: "technology",
    definition: "no longer used or useful because something newer has replaced it",
    example: "Printed encyclopaedias became {obsolete} almost overnight.",
    collocations: ["render obsolete", "technologically obsolete", "become obsolete"],
    synonyms: ["outdated", "outmoded"] },
  { id: "innovation", word: "innovation", pos: "noun", band: 6, topic: "technology",
    definition: "a new method or product, or the process of creating them",
    example: "Government funding drove much of the {innovation} behind the internet.",
    collocations: ["technological innovation", "foster innovation", "a major innovation"],
    synonyms: ["breakthrough", "invention"] },
  { id: "surveillance", word: "surveillance", pos: "noun", band: 7, topic: "technology",
    definition: "the careful watching of people or places, often using cameras or data",
    example: "Critics warn that constant {surveillance} erodes personal freedom.",
    collocations: ["mass surveillance", "under surveillance", "surveillance cameras"],
    synonyms: ["monitoring", "observation"] },
  { id: "connectivity", word: "connectivity", pos: "noun", band: 7, topic: "technology",
    definition: "the ability of devices or places to connect to a network or to each other",
    example: "Poor rural {connectivity} kept many students out of online lessons.",
    collocations: ["internet connectivity", "improve connectivity", "high-speed connectivity"],
    synonyms: ["access", "linkage"] },
  { id: "algorithm", word: "algorithm", pos: "noun", band: 7, topic: "technology",
    definition: "a set of rules a computer follows to solve a problem or make a decision",
    example: "The {algorithm} decides which stories appear at the top of the feed.",
    collocations: ["a recommendation algorithm", "algorithmic bias", "tweak the algorithm"],
    synonyms: ["procedure", "formula"] },
  { id: "disruptive", word: "disruptive", pos: "adjective", band: 8, topic: "technology",
    definition: "causing radical change to an existing industry or way of doing things",
    example: "Streaming proved more {disruptive} to cinemas than anyone expected.",
    collocations: ["disruptive technology", "highly disruptive", "disruptive innovation"],
    synonyms: ["transformative", "groundbreaking"],
    note: "In business writing it is positive; in everyday English it can mean simply 'causing trouble'." },
  { id: "redundant", word: "redundant", pos: "adjective", band: 8, topic: "technology",
    definition: "no longer needed, especially describing a worker whose job has been removed",
    example: "Hundreds of clerical staff were made {redundant} when the system was installed.",
    collocations: ["make someone redundant", "become redundant", "redundant skills"],
    synonyms: ["unnecessary", "surplus"] },

  // ─── Health ──────────────────────────────────────────────────────────────
  { id: "sedentary", word: "sedentary", pos: "adjective", band: 8, topic: "health",
    definition: "involving a lot of sitting and little physical activity",
    example: "Office work encourages a {sedentary} lifestyle that harms long-term health.",
    collocations: ["a sedentary lifestyle", "sedentary work", "increasingly sedentary"],
    synonyms: ["inactive", "desk-bound"] },
  { id: "epidemic", word: "epidemic", pos: "noun", band: 6, topic: "health",
    definition: "a sudden widespread occurrence of a disease, or of an undesirable phenomenon",
    example: "Doctors describe childhood obesity as a slow-moving {epidemic}.",
    collocations: ["a global epidemic", "contain an epidemic", "an obesity epidemic"],
    synonyms: ["outbreak", "plague"],
    note: "An epidemic is regional; a pandemic crosses continents." },
  { id: "nutrition", word: "nutrition", pos: "noun", band: 6, topic: "health",
    definition: "the process of getting the food needed for health and growth",
    example: "School meals are often a child's main source of proper {nutrition}.",
    collocations: ["poor nutrition", "nutrition education", "nutritional value"],
    synonyms: ["nourishment", "diet"] },
  { id: "wellbeing", word: "wellbeing", pos: "noun", band: 7, topic: "health",
    definition: "the state of being comfortable, healthy and happy",
    example: "Employers increasingly monitor the mental {wellbeing} of their staff.",
    collocations: ["mental wellbeing", "promote wellbeing", "a sense of wellbeing"],
    synonyms: ["welfare", "quality of life"] },
  { id: "preventive", word: "preventive", pos: "adjective", band: 7, topic: "health",
    definition: "intended to stop a problem, especially illness, before it happens",
    example: "Spending on {preventive} care reduces hospital admissions later.",
    collocations: ["preventive medicine", "preventive measures", "preventive care"],
    synonyms: ["precautionary", "pre-emptive"],
    note: "Preventive and preventative are both correct; preventive is more common in writing." },
  { id: "chronic", word: "chronic", pos: "adjective", band: 7, topic: "health",
    definition: "lasting for a long time and difficult to cure or stop",
    example: "{Chronic} conditions such as diabetes absorb most of the health budget.",
    collocations: ["chronic illness", "chronic pain", "chronic shortage"],
    synonyms: ["persistent", "long-term"],
    note: "The opposite is acute (severe but short). Also used outside medicine: a chronic shortage of housing." },
  { id: "immunity", word: "immunity", pos: "noun", band: 7, topic: "health",
    definition: "the body's ability to resist a particular infection",
    example: "Vaccination programmes build {immunity} across the whole population.",
    collocations: ["build immunity", "natural immunity", "herd immunity"],
    synonyms: ["resistance", "protection"] },
  { id: "stigma", word: "stigma", pos: "noun", band: 8, topic: "health",
    definition: "strong social disapproval attached to a condition or characteristic",
    example: "The {stigma} surrounding mental illness stops many people seeking help.",
    collocations: ["social stigma", "attach stigma to", "reduce the stigma"],
    synonyms: ["shame", "disgrace"] },

  // ─── Urbanisation ────────────────────────────────────────────────────────
  { id: "congestion", word: "congestion", pos: "noun", band: 6, topic: "urbanisation",
    definition: "a situation in which a place is too crowded, especially with traffic",
    example: "Road pricing has cut {congestion} in the city centre by a fifth.",
    collocations: ["traffic congestion", "ease congestion", "a congestion charge"],
    synonyms: ["overcrowding", "gridlock"] },
  { id: "infrastructure", word: "infrastructure", pos: "noun", band: 6, topic: "urbanisation",
    definition: "the basic systems a country needs to work, such as roads, power and water",
    example: "Rapid growth has outpaced investment in {infrastructure}.",
    collocations: ["transport infrastructure", "invest in infrastructure", "ageing infrastructure"],
    synonyms: ["facilities", "public works"] },
  { id: "commute", word: "commute", pos: "verb", band: 6, topic: "urbanisation",
    definition: "to travel regularly between home and work",
    example: "Thousands {commute} into the capital from towns an hour away.",
    collocations: ["commute to work", "a daily commute", "a long commute"],
    synonyms: ["travel to work", "journey"] },
  { id: "urban-sprawl", word: "urban sprawl", pos: "phrase", band: 8, topic: "urbanisation",
    definition: "the uncontrolled spread of a city into the countryside around it",
    example: "{Urban sprawl} has swallowed farmland on the edge of the city.",
    collocations: ["limit urban sprawl", "unchecked sprawl", "suburban sprawl"],
    synonyms: ["overdevelopment", "expansion"] },
  { id: "densely-populated", word: "densely populated", pos: "phrase", band: 7, topic: "urbanisation",
    definition: "having a large number of people living in each unit of area",
    example: "The most {densely populated} districts have the fewest parks.",
    collocations: ["densely populated areas", "a densely populated city"],
    synonyms: ["crowded", "heavily populated"],
    note: "The opposite is sparsely populated." },
  { id: "amenities", word: "amenities", pos: "noun", band: 7, topic: "urbanisation",
    definition: "useful or pleasant facilities in a place, such as shops, parks and libraries",
    example: "New estates are often built before any local {amenities} exist.",
    collocations: ["local amenities", "public amenities", "basic amenities"],
    synonyms: ["facilities", "services"] },
  { id: "affordability", word: "affordability", pos: "noun", band: 7, topic: "urbanisation",
    definition: "the degree to which something is cheap enough for people to pay for",
    example: "Housing {affordability} has worsened faster than wages have grown.",
    collocations: ["housing affordability", "an affordability crisis", "improve affordability"],
    synonyms: ["cost", "accessibility"] },
  { id: "pedestrianise", word: "pedestrianise", pos: "verb", band: 8, topic: "urbanisation",
    definition: "to make a street or area for walkers only, by banning vehicles",
    example: "The council voted to {pedestrianise} the historic quarter.",
    collocations: ["pedestrianise the centre", "a pedestrianised zone"],
    synonyms: ["close to traffic", "make car-free"] },

  // ─── Work ────────────────────────────────────────────────────────────────
  { id: "remuneration", word: "remuneration", pos: "noun", band: 8, topic: "work",
    definition: "money paid for work; pay, in formal language",
    example: "The role offers generous {remuneration} but demands long hours.",
    collocations: ["generous remuneration", "a remuneration package", "adequate remuneration"],
    synonyms: ["pay", "compensation"] },
  { id: "incentive", word: "incentive", pos: "noun", band: 6, topic: "work",
    definition: "something that encourages a person to do something",
    example: "Tax breaks act as an {incentive} for firms to train young workers.",
    collocations: ["a financial incentive", "provide an incentive", "little incentive"],
    synonyms: ["motivation", "inducement"] },
  { id: "workforce", word: "workforce", pos: "noun", band: 6, topic: "work",
    definition: "all the people who work for a company or in a country",
    example: "Women now make up half the {workforce} in most developed economies.",
    collocations: ["a skilled workforce", "the global workforce", "reduce the workforce"],
    synonyms: ["staff", "labour force"] },
  { id: "burnout", word: "burnout", pos: "noun", band: 7, topic: "work",
    definition: "extreme tiredness caused by working too hard for too long",
    example: "Nurses reported record levels of {burnout} after the crisis.",
    collocations: ["suffer burnout", "avoid burnout", "widespread burnout"],
    synonyms: ["exhaustion", "fatigue"] },
  { id: "autonomy", word: "autonomy", pos: "noun", band: 8, topic: "work",
    definition: "freedom to make your own decisions about how you work",
    example: "Staff given greater {autonomy} tend to stay with the company longer.",
    collocations: ["a degree of autonomy", "greater autonomy", "professional autonomy"],
    synonyms: ["independence", "self-governance"] },
  { id: "productivity", word: "productivity", pos: "noun", band: 6, topic: "work",
    definition: "the rate at which work is completed or goods are produced",
    example: "Shorter weeks raised {productivity} in every trial company.",
    collocations: ["boost productivity", "productivity growth", "low productivity"],
    synonyms: ["efficiency", "output"] },
  { id: "outsourcing", word: "outsourcing", pos: "noun", band: 7, topic: "work",
    definition: "the practice of paying an outside company to do work your own staff used to do",
    example: "{Outsourcing} customer service abroad cut costs but damaged the brand.",
    collocations: ["outsourcing of jobs", "offshore outsourcing"],
    synonyms: ["contracting out", "subcontracting"] },
  { id: "meritocracy", word: "meritocracy", pos: "noun", band: 8, topic: "work",
    definition: "a system in which people advance because of ability rather than background",
    example: "The company claims to be a {meritocracy}, yet most directors share one school.",
    collocations: ["a true meritocracy", "the myth of meritocracy"],
    synonyms: ["rule by ability"] },

  // ─── Globalisation ───────────────────────────────────────────────────────
  { id: "multinational", word: "multinational", pos: "adjective", band: 6, topic: "globalisation",
    definition: "operating in several countries at once",
    example: "A handful of {multinational} corporations dominate the coffee trade.",
    collocations: ["a multinational corporation", "multinational companies"],
    synonyms: ["international", "global"] },
  { id: "tariff", word: "tariff", pos: "noun", band: 7, topic: "globalisation",
    definition: "a tax charged on goods coming into a country",
    example: "The government imposed a 20% {tariff} on imported steel.",
    collocations: ["impose a tariff", "tariff barriers", "lift tariffs"],
    synonyms: ["duty", "import tax"] },
  { id: "homogenisation", word: "homogenisation", pos: "noun", band: 8, topic: "globalisation",
    definition: "the process by which different things become the same as each other",
    example: "Global brands have led to a {homogenisation} of high streets worldwide.",
    collocations: ["cultural homogenisation", "the homogenisation of culture"],
    synonyms: ["standardisation", "uniformity"] },
  { id: "migration", word: "migration", pos: "noun", band: 6, topic: "globalisation",
    definition: "the movement of people from one place to another to live or work",
    example: "Economic {migration} has reshaped the workforce of several European cities.",
    collocations: ["mass migration", "economic migration", "migration patterns"],
    synonyms: ["movement", "relocation"] },
  { id: "interdependence", word: "interdependence", pos: "noun", band: 8, topic: "globalisation",
    definition: "a situation in which two or more countries or groups depend on each other",
    example: "The pandemic exposed the {interdependence} of global supply chains.",
    collocations: ["economic interdependence", "growing interdependence"],
    synonyms: ["mutual reliance", "interconnection"] },
  { id: "exploitation", word: "exploitation", pos: "noun", band: 7, topic: "globalisation",
    definition: "the unfair use of people or resources for profit",
    example: "Cheap clothing often depends on the {exploitation} of factory workers.",
    collocations: ["labour exploitation", "prevent exploitation", "ruthless exploitation"],
    synonyms: ["abuse", "misuse"] },
  { id: "assimilation", word: "assimilation", pos: "noun", band: 8, topic: "globalisation",
    definition: "the process of becoming part of a society and adopting its customs",
    example: "Language classes are central to the {assimilation} of new arrivals.",
    collocations: ["cultural assimilation", "forced assimilation"],
    synonyms: ["integration", "absorption"],
    note: "Integration suggests keeping your own culture too; assimilation suggests replacing it." },
  { id: "remittances", word: "remittances", pos: "noun", band: 8, topic: "globalisation",
    definition: "money sent home by people working in another country",
    example: "{Remittances} from abroad exceed foreign aid in several economies.",
    collocations: ["send remittances", "remittance flows"],
    synonyms: ["transfers", "money sent home"] },

  // ─── Media ───────────────────────────────────────────────────────────────
  { id: "censorship", word: "censorship", pos: "noun", band: 6, topic: "media",
    definition: "the removal of parts of books, films or news that authorities object to",
    example: "State {censorship} left readers unaware of the protests.",
    collocations: ["strict censorship", "impose censorship", "media censorship"],
    synonyms: ["suppression", "restriction"] },
  { id: "bias", word: "bias", pos: "noun", band: 6, topic: "media",
    definition: "an unfair preference for or against someone or something",
    example: "Readers accused the paper of political {bias} in its election coverage.",
    collocations: ["political bias", "an inherent bias", "free from bias"],
    synonyms: ["prejudice", "partiality"] },
  { id: "credibility", word: "credibility", pos: "noun", band: 7, topic: "media",
    definition: "the quality of being believed or trusted",
    example: "A single fabricated story destroyed the channel's {credibility}.",
    collocations: ["lose credibility", "lend credibility to", "scientific credibility"],
    synonyms: ["trustworthiness", "reliability"] },
  { id: "sensationalism", word: "sensationalism", pos: "noun", band: 8, topic: "media",
    definition: "the presentation of news in a shocking way to attract attention",
    example: "Tabloid {sensationalism} turned a minor dispute into a national scandal.",
    collocations: ["tabloid sensationalism", "resort to sensationalism"],
    synonyms: ["exaggeration", "hype"] },
  { id: "coverage", word: "coverage", pos: "noun", band: 6, topic: "media",
    definition: "the reporting of an event by newspapers, television or online media",
    example: "The trial received blanket {coverage} for three weeks.",
    collocations: ["media coverage", "extensive coverage", "blanket coverage"],
    synonyms: ["reporting", "airtime"] },
  { id: "propaganda", word: "propaganda", pos: "noun", band: 7, topic: "media",
    definition: "information, often misleading, spread to promote a political cause",
    example: "Wartime {propaganda} portrayed the enemy as barely human.",
    collocations: ["state propaganda", "spread propaganda", "a propaganda campaign"],
    synonyms: ["indoctrination", "spin"] },
  { id: "misinformation", word: "misinformation", pos: "noun", band: 7, topic: "media",
    definition: "false information that is spread, whether or not the intention is to deceive",
    example: "Health {misinformation} circulated faster than official advice.",
    collocations: ["spread misinformation", "combat misinformation", "online misinformation"],
    synonyms: ["falsehood", "inaccuracy"],
    note: "Disinformation is deliberate; misinformation may simply be a mistake." },
  { id: "scrutiny", word: "scrutiny", pos: "noun", band: 8, topic: "media",
    definition: "careful and critical examination of someone or something",
    example: "Public figures face intense {scrutiny} of their private lives.",
    collocations: ["come under scrutiny", "close scrutiny", "public scrutiny"],
    synonyms: ["examination", "inspection"] },
];

export const wordById = Object.fromEntries(words.map((w) => [w.id, w])) as Record<string, WordEntry>;

export const wordsByTopic = (topic: TopicId) => words.filter((w) => w.topic === topic);

/** "A {curriculum} is…" → "A curriculum is…" */
export const plain = (s: string) => s.replace(/\{([^}]+)\}/g, "$1");

/** "A {curriculum} is…" → "A ________ is…" */
export const blanked = (s: string) => s.replace(/\{[^}]+\}/g, "  ______  ");
